insert into miscellany (property, value) values
    ('maintainer', 'IrishMace'),
    ('email', 'kcalcagno@alumni.nd.edu'),
    ('year', '2024');

insert into game (game_id, opponent, short_name, conference) values
    (1, 'Niagara', 'Niag', 0),
    (2, 'Western Carolina', 'WCU', 0),
    (3, 'Auburn (Legends Classic)', 'Aub (Legends)', 0),
    (4, 'Maryland-Eastern Shore', 'UMES', 0),
    (5, 'at South Carolina', '@SC', 0),
    (6, 'at Miami', '@Mia', 1),
    (7, 'Western Michigan', 'UWM', 0),
    (8, 'at Marquette', '@Marq', 0),
    (9, 'Georgetown', 'GU', 0),
    (10, 'The Citadel', 'Cit', 0),
    (11, 'Marist College', 'Mar', 0),
    (12, 'Virginia', 'UVa', 1),
    (13, 'North Carolina St.', 'NCSU', 1),
    (14, 'Duke', 'Duke', 1),
    (15, 'at Georgia Tech', '@GT', 1),
    (16, 'Florida St.', 'FSU', 1),
    (17, 'at Boston College', '@BC', 1),
    (18, 'Miami', 'Mia', 1),
    (19, 'Boston College', 'BC', 1),
    (20, 'Virginia', '@UVa', 1),
    (21, 'at Pittsburgh', '@Pitt', 1),
    (22, 'at Duke', '@Duke', 1),
    (23, 'Virginia Tech', 'VT', 1),
    (24, 'Georgia Tech', 'GT', 1),
    (25, 'at Louisville', '@UL', 1),
    (26, 'at Syracuse', '@Syr', 1),
    (27, 'Wake Forest', 'WFU', 1),
    (28, 'Clemson', 'Clem', 1),
    (29, 'at North Carolina', '@UNC', 1),
    (30, 'at Virginia Tech', '@VT', 1);
    