insert into miscellany (property, value) values
    ('maintainer', 'IrishMace'),
    ('email', 'kcalcagno@alumni.nd.edu'),
    ('year', '2026');

insert into game (game_id, opponent, short_name, conference) values
    (1, 'Long Island', 'LIU', 0),
    (2, 'Detroit Mercy', 'Det', 0),
    (3, 'Eastern Illinois', 'EIU', 0),
    (4, 'at Ohio State', '@OSU', 0),
    (5, 'Bellarmine', 'Bell', 0),
    (6, 'Kansas (Players Era)', 'KU (Players)', 0),
    (7, 'Rutgers (Players Era)', 'RU (Players)', 0),
    (8, 'TBD (Players Era)', 'TBD (Players)', 0),
    (9, 'Missouri (SEC/ACC Challenge)', 'Mizz (SEC/ACC)', 0),
    (10, 'at Texas Christian', '@TCU', 0),
    (11, 'Idaho', 'Idaho', 0),
    (12, 'Evansville', 'Evan', 0),
    (13, 'Purdue Fort Wayne', 'PFW', 0),
    (14, 'at Stanford', '@Stan', 1),
    (15, 'at California', '@Cal', 1),
    (16, 'Clemson', 'Clem', 1),
    (17, 'Miami', 'Mia', 1),
    (18, 'at Virginia Tech', '@VT', 1),
    (19, 'at North Carolina', '@UNC', 1),
    (20, 'Boston College', 'BC', 1),
    (21, 'Virginia', 'UVa', 1),
    (22, 'at Syracuse', '@Syr', 1),
    (23, 'at Louisville', '@UL', 1),
    (24, 'Florida State', 'FSU', 1),
    (25, 'at Southern Methodist', '@SMU', 1),
    (26, 'Georgia Tech', 'GT', 1),
    (27, 'at Pittsburgh', '@Pitt', 1),
    (28, 'Duke', 'Duke', 1),
    (29, 'North Carolina State', 'NCSU', 1),
    (30, 'Stanford', 'Stan', 1),
    (31, 'at Boston College', '@BC', 1);
