insert into miscellany (property, value) values
    ('maintainer', 'IrishMace'),
    ('email', 'kcalcagno@alumni.nd.edu'),
    ('year', '2022');

insert into game (game_id, opponent, short_name, conference) values
    (1, 'Cal State Northridge', 'CSUN', 0),
    (2, 'High Point', 'HPU', 0),
    (3, 'St. Mary''s (Maui Invitational)', 'SMC (Maui)', 0),
    (4, 'TBD (Maui Invitational)', 'TBD (Maui)', 0),
    (5, 'TBD (Maui Invitational)', 'TBD (Maui)', 0),
    (6, 'at Illinois (ACC/B1G Challenge)', '@Ill (ACC/B1G)', 0),
    (7, 'at Boston College', '@BC', 1),
    (8, 'Kentucky', 'UK', 0),
    (9, 'Indiana (Crossroads)', 'IU (Xroads)', 0),
    (10, 'Western Michigan', 'WMU', 0),
    (11, 'Texas A&M Corpus Christi', 'TAMCC', 0),
    (12, 'at Pittsburgh', '@Pitt', 1),
    (13, 'Duke', 'Duke', 1),
    (14, 'North Carolina', '@NC', 1),
    (15, 'at Georgia Tech', '@GT', 1),
    (16, 'Clemson', 'Clem', 1),
    (17, 'at Virginia Tech', '@VT', 1),
    (18, 'at Howard', '@How', 0),
    (19, 'at Louisville', '@UL', 1),
    (20, 'North Carolina St.', 'NCSU', 1),
    (21, 'Virginia', 'UVa', 1),
    (22, 'at Miami', '@Mia', 1),
    (23, 'at North Carolina St.', '@NCSU', 1),
    (24, 'Louisville', 'UL', 1),
    (25, 'at Clemson', '@Clem', 1),
    (26, 'Boston College', 'BC', 1),
    (27, 'at Wake Forest', '@WFU', 1),
    (28, 'Syracuse', 'Syr', 1),
    (29, 'Georgia Tech', 'GT', 1),
    (30, 'at Florida St.', '@FSU', 1),
    (31, 'Pittsburgh', 'Pitt', 1);
